name: Add a city or flag an aggregator
description: Add your city to the community calendar
title: "Add city: NAME with aggregators: "
labels: ["city-request"]
body:
  - type: markdown
    attributes:
      value: |
        Just edit the title! Replace NAME with your city, and list any aggregators (newspapers, regional event platforms) after "aggregators:". If you're not sure what counts as an aggregator, just leave it blank and we'll help you figure it out.
