#!/usr/bin/env python3
"""Create the directory structure for a new city.

Creates:
  cities/<city>/pending_feeds.txt  — template for adding feeds
  cities/<city>/city.conf          — geo-filtering config (needs editing)
  cities/<city>/feeds.txt          — empty (generated from DB by build)
  cities/<city>/SOURCES_CHECKLIST.md — template for documenting sources

Usage:
    python scripts/add_city.py asheville NC
    python scripts/add_city.py "raleighdurham" NC    # multi-city, no spaces
    python scripts/add_city.py toronto ON --country CA
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent


def main():
    parser = argparse.ArgumentParser(description="Create directory structure for a new city")
    parser.add_argument("city", help="City name (lowercase, no spaces, e.g. 'santarosa')")
    parser.add_argument("state", help="State/province abbreviation (e.g. NC, CA, ON)")
    parser.add_argument("--country", default="US", help="Country code (default: US)")
    args = parser.parse_args()

    city = args.city.lower().replace(" ", "")
    city_dir = ROOT / "cities" / city

    if city_dir.exists():
        print(f"Error: cities/{city}/ already exists")
        sys.exit(1)

    city_dir.mkdir(parents=True)
    print(f"Created cities/{city}/")

    # pending_feeds.txt
    (city_dir / "pending_feeds.txt").write_text(f"""\
# Add feed URLs or scraper outputs here. The build will process them into the
# database automatically and reset this file to the template below.
#
# Format:
#   # Source Name
#   https://example.com/events/?ical=1
#
# Or for scrapers:
#   # Source Name
#   # cmd: python scrapers/example.py --name "Source Name"
#   cities/{city}/example.ics
#
# Test before adding:
#   python scripts/add_feed.py URL {city} "Source Name" --test
#   python scripts/add_scraper.py example {city} "Source Name" --test
#
# See CONTRIBUTING.md for details.
""")
    print(f"  pending_feeds.txt (template)")

    # feeds.txt (empty, generated by build)
    (city_dir / "feeds.txt").write_text(f"""\
# {city.title()} - source inventory
# Generated from feeds table. Do not edit manually.
# To add feeds, use pending_feeds.txt in this directory.
""")
    print(f"  feeds.txt (empty, generated by build)")

    # city.conf
    (city_dir / "city.conf").write_text(f"""\
# radius: 25
# state: {args.state}
#
# Add nearby city names below (one per line).
# Run: python scripts/geocode_cities.py --city {city}
# See docs/procedures.md section 5 for details.
""")
    print(f"  city.conf (edit to add nearby cities, then run geocode_cities.py)")

    # SOURCES_CHECKLIST.md
    display = city.replace("-", " ").title()
    (city_dir / "SOURCES_CHECKLIST.md").write_text(f"""\
# {display} Sources Checklist

## Currently Implemented

| Source | Type | Events | URL |
|--------|------|--------|-----|

## Discovered - Ready to Add

| Source | Feed URL | Events | Notes |
|--------|----------|--------|-------|

## Needs Scraper

| Source | URL | Approach | Notes |
|--------|-----|----------|-------|

## Non-Starters

| Source | Reason |
|--------|--------|

## To Investigate

- [ ] Meetup groups
- [ ] Local library system
- [ ] City/county government calendar
- [ ] University events
- [ ] Local arts/music venues

---

See [docs/procedures.md](../../docs/procedures.md) for discovery techniques.
""")
    print(f"  SOURCES_CHECKLIST.md (template)")

    print(f"\nNext steps:")
    print(f"  1. Search for feeds: see docs/procedures.md")
    print(f"  2. Add feeds to cities/{city}/pending_feeds.txt")
    print(f"  3. Edit cities/{city}/city.conf with nearby cities")
    print(f"  4. Run: python scripts/geocode_cities.py --city {city}")
    print(f"  5. Register in cities.json and xmlui/Main.xmlui")


if __name__ == "__main__":
    main()
