create table if not exists public.chat_beta_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  city text not null,
  latest_user_text text not null,
  request_messages jsonb not null default '[]'::jsonb,
  intent_plan jsonb,
  planner_model text not null,
  reply_model text not null,
  planner_raw text,
  planner_error text,
  executed_sql text not null,
  query_error text,
  used_fallback boolean not null default false,
  planner_fallback_used boolean not null default false,
  query_fallback_used boolean not null default false,
  candidate_ids bigint[] not null default '{}'::bigint[],
  recommended_ids bigint[] not null default '{}'::bigint[],
  reply_text text not null,
  reply_raw text,
  reply_error text
);

create index if not exists chat_beta_logs_city_created_at_idx
  on public.chat_beta_logs (city, created_at desc);

create index if not exists chat_beta_logs_user_created_at_idx
  on public.chat_beta_logs (user_id, created_at desc);

alter table public.chat_beta_logs enable row level security;

create policy "chat_beta_logs service role manages all"
on public.chat_beta_logs
for all
to service_role
using (true)
with check (true);
