-- pending_feeds: feeds submitted by admins via the UI, awaiting next build
CREATE TABLE pending_feeds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text NOT NULL,
  url text NOT NULL,
  name text NOT NULL,
  fallback_url text,
  added_by uuid REFERENCES auth.users(id),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'rejected', 'removed')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE pending_feeds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin users can manage pending_feeds"
  ON pending_feeds FOR ALL
  USING (auth.uid() IN (SELECT user_id FROM admin_users));

CREATE POLICY "Anon read for build"
  ON pending_feeds FOR SELECT
  USING (true);
